import type { ApForm } from "../_add-property/data";

export * from "../_add-property/data";

export const INITIAL: ApForm = {
  listing: "sale",
  type: "Villa",
  title: "Olive Grove Estate",
  description: "A serene four-bedroom villa set among mature olive trees in Ankawa. Floor-to-ceiling glazing fills the open-plan living spaces with golden afternoon light, while the landscaped garden and shaded terrace make for effortless entertaining.",
  price: "450000",
  currency: "USD",
  area: "420",
  areaUnit: "sqm",
  beds: 3,
  baths: 2,
  parking: 2,
  condition: "Good",
  furnished: "no",
  year: "2022",
  short: "",
  furnishing: "Semi-furnished",
  floors: 2,
  orientation: "South facing",
  amenities: ["Swimming pool", "Garden", "Security", "Central AC"],
  customAmenities: ["Rooftop terrace"],
  highlights: "",
  city: "Erbil",
  district: "Ankawa",
  project: "",
  street: "60 Meter Street, Block 4",
  building: "Villa 128",
  lat: "36.19085",
  lng: "44.00947",
  locNotes: "Set back from the main road behind the olive grove; gated entrance on the north side.",
  tourUrl: "https://my.matterport.com/show/?m=olive-grove",
  ownerName: "Hêmin Abdullah",
  ownerPhone: "+964 750 412 8890",
  ownerEmail: "hemin@email.com",
  agent: "lana",
  internalNotes: "Owner is flexible on price for a quick close. Keys held at the Ankawa office; 24h notice for viewings.",
};
